# Generated by Django 6.1.1 on 2026-09-29 17:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('business', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(help_text='e.g. ANM-2026-01042', max_length=50, unique=True)),
                ('current_stage', models.CharField(choices=[('Draft', 'Draft Application'), ('Submitted', 'Application Submitted'), ('Documents Verified', 'Documents Verified'), ('Under Review', 'Department Review / Technical Scrutiny'), ('Clarification Required', 'Clarification Required'), ('Inspection Scheduled', 'Field Inspection Scheduled'), ('Inspection Completed', 'Inspection Completed'), ('Approved', 'Approval Granted by Authority'), ('Rejected', 'Application Rejected')], default='Submitted', max_length=50)),
                ('current_department', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('Normal', 'Standard Processing'), ('High', 'High Priority'), ('Urgent', 'Urgent / Escalated')], default='Normal', max_length=20)),
                ('assigned_officer_name', models.CharField(blank=True, default='Dr. Rajesh Kulkarni', max_length=150)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sla_days_total', models.PositiveIntegerField(default=30)),
                ('sla_days_remaining', models.IntegerField(default=15)),
                ('is_delayed', models.BooleanField(default=False)),
                ('progress_percent', models.PositiveIntegerField(default=40)),
                ('officer_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='approvals.approval')),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='business.businessprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(default='PDF', max_length=50)),
                ('status', models.CharField(choices=[('Verified', 'Verified ✓'), ('Pending', 'Pending Scrutiny ○'), ('Action Required', 'Action Required ⚠')], default='Pending', max_length=30)),
                ('officer_feedback', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_rel', to='applications.application')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_links', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=100)),
                ('new_status', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='applications.application')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('query_text', models.TextField()),
                ('response_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Open', 'Open Query / Awaiting Entrepreneur Response'), ('Responded', 'Response Provided by Entrepreneur'), ('Resolved', 'Clarification Accepted & Resolved')], default='Open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='applications.application')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
