# Generated by Django 6.1.1 on 2026-09-29 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('approval_ref', models.CharField(help_text='e.g. DISH-LIC-2025-8841', max_length=100)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Compliant', 'Compliant ✓'), ('Approaching', 'Renewal Approaching ⏰'), ('Urgent', 'Urgent Action Required ⚠'), ('Overdue', 'Overdue / Non-Compliant ✕')], default='Approaching', max_length=30)),
                ('annual_fee', models.CharField(default='₹15,000', max_length=100)),
                ('penalties', models.CharField(default='Statutory late fee of ₹500/week after due date', max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliances', to='approvals.approval')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='business.businessprofile')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_due_date', models.DateField()),
                ('renewal_submitted_date', models.DateField(blank=True, null=True)),
                ('renewal_fee_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming Renewal Notice'), ('Submitted', 'Renewal Application Submitted'), ('Approved', 'Renewal Approved & Extended'), ('Delayed', 'Action Delayed')], default='Upcoming', max_length=30)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='compliance.compliance')),
            ],
            options={
                'ordering': ['-renewal_due_date'],
            },
        ),
    ]
