# Generated by Django 6.1.1 on 2026-09-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(default='Directorate of Industries, Maharashtra', max_length=255)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('benefits', models.TextField()),
                ('max_subsidy', models.CharField(default='Up to 50% capital subsidy / ₹1 Crore', max_length=150)),
                ('deadline', models.CharField(default='Open Round the Year / FY 2026-27', max_length=100)),
                ('official_source', models.URLField(default='https://di.maharashtra.gov.in', max_length=300)),
                ('category_tag', models.CharField(choices=[('MSME', 'Micro, Small & Medium Enterprises (MSME)'), ('Large', 'Large & Mega Industrial Projects'), ('Agro-Food', 'Agro & Food Processing Special Incentives'), ('Women/SC/ST', 'Women / SC / ST Entrepreneurs'), ('Green Tech', 'Green Technology & Sustainability')], default='MSME', max_length=50)),
                ('min_investment_cr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_investment_cr', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('applicable_districts', models.TextField(default='All Districts of Maharashtra with enhanced rates for Zone C, D, D+')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
