# Generated by Django 6.1.1 on 2026-09-29 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notif_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Action Required'), ('success', 'Approval / Clearance'), ('urgent', 'Urgent Deadline')], default='info', max_length=20)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('entrepreneur', 'Entrepreneur / Business Owner'), ('officer', 'Government Officer / Reviewing Authority')], default='entrepreneur', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, help_text='e.g. Joint Director of Industries (Nashik Region)', max_length=150)),
                ('department', models.CharField(blank=True, help_text='e.g. Directorate of Industries, Government of Maharashtra', max_length=200)),
                ('office_location', models.CharField(blank=True, help_text='e.g. DIC Trimbak Road, Nashik', max_length=200)),
                ('officer_id', models.CharField(blank=True, help_text='e.g. MAH-IND-OFF-0442', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
