# Generated by Django 6.1.1 on 2026-09-29 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('pan', 'PAN Card / Tax Identity'), ('gst', 'GST Registration Certificate'), ('company_reg', 'Certificate of Incorporation / Partnership Deed'), ('land_deed', 'Land Ownership / MIDC Allotment Deed'), ('factory_plan', 'Architectural Factory Layout Plan'), ('environmental_noc', 'Environmental Management Plan / ETP Specs'), ('fire_layout', 'Fire Hydrant & Evacuation Layout Plan'), ('electricity_sld', 'Electrical Single Line Diagram (SLD)'), ('water_report', 'Water Potability & Effluent Analysis Report'), ('other', 'Supporting Statutory Annexure')], default='pan', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('file_size_kb', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('status', models.CharField(choices=[('Uploaded', 'Uploaded — Pending Analysis'), ('Pre-validated', 'Pre-validated by AnumatiSetu'), ('Action Required', 'Action Required — Review Flagged'), ('Verified', 'Department Verified'), ('Rejected', 'Incomplete / Invalid')], default='Uploaded', max_length=30)),
                ('is_ocr_processed', models.BooleanField(default=False)),
                ('ocr_extracted_text', models.TextField(blank=True)),
                ('ocr_confidence_score', models.FloatField(default=0.0)),
                ('validation_notes', models.TextField(blank=True, help_text='AI and algorithmic pre-check notes')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='business.businessprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
