# Generated by Django 6.1.1 on 2026-09-29 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='e.g. Amol Foods Pvt. Ltd.', max_length=200)),
                ('business_type', models.CharField(choices=[('Pvt Ltd', 'Private Limited Company'), ('LLP', 'Limited Liability Partnership (LLP)'), ('Partnership', 'Registered Partnership Firm'), ('Proprietorship', 'Sole Proprietorship'), ('Public Ltd', 'Public Limited Company')], default='Pvt Ltd', max_length=50)),
                ('industry_sector', models.CharField(choices=[('Food Processing', 'Agro & Food Processing'), ('Manufacturing', 'Heavy Engineering & Manufacturing'), ('Automobile', 'Automobile & Auto-components'), ('Pharmaceuticals', 'Pharmaceuticals & Life Sciences'), ('Chemical', 'Chemicals & Petrochemicals'), ('Textile', 'Textile, Apparel & Technical Textiles'), ('IT & Electronics', 'Information Technology & Electronics'), ('Renewable Energy', 'Renewable Energy & Green Tech'), ('Warehousing', 'Logistics, Warehousing & Cold Chain')], default='Food Processing', max_length=100)),
                ('location', models.CharField(default='Nashik, Maharashtra', max_length=150)),
                ('address', models.TextField(blank=True, default='Plot B-42, Satpur MIDC Industrial Area, Nashik - 422007')),
                ('district', models.CharField(default='Nashik', max_length=100)),
                ('investment_cr', models.DecimalField(decimal_places=2, default=5.0, help_text='Proposed investment in Crores INR (e.g. 5.00)', max_digits=10)),
                ('employees_count', models.PositiveIntegerField(default=120, help_text='Total projected workforce/employees')),
                ('project_stage', models.CharField(choices=[('New Greenfield Unit', 'Setting Up New Greenfield Unit'), ('Expansion Unit', 'Substantial Expansion of Existing Unit'), ('Land Acquired', 'Pre-Construction / Land Acquired'), ('Operational Modernization', 'Operational Modernization & Technology Upgradation')], default='New Greenfield Unit', max_length=100)),
                ('registration_no', models.CharField(blank=True, default='MH-NSK-2026-8942', max_length=100)),
                ('udyam_no', models.CharField(blank=True, default='UDYAM-MH-26-0045891', max_length=100)),
                ('pan_number', models.CharField(blank=True, default='AABCA1234F', max_length=20)),
                ('gst_number', models.CharField(blank=True, default='27AABCA1234F1Z5', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
