# Generated by Django 6.1.1 on 2026-09-29 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('inspector_name', models.CharField(default='Er. Sachin Deshmukh', max_length=150)),
                ('inspector_designation', models.CharField(default='Divisional Safety & Environmental Inspector', max_length=150)),
                ('location', models.CharField(default='Plot B-42, Satpur MIDC Industrial Area, Nashik', max_length=255)),
                ('scheduled_date', models.DateField()),
                ('time_slot', models.CharField(default='11:00 AM – 01:30 PM', max_length=100)),
                ('inspection_type', models.CharField(choices=[('Pre-Establishment Site Visit', 'Pre-Establishment Site Inspection'), ('Pollution Compliance Audit', 'Pollution Control & ETP Audit'), ('Fire Safety Verification', 'Fire Safety & Hydrant Simulation'), ('Factory Layout Inspection', 'Factory Layout & Safety Clearances'), ('Joint Departmental Inspection', 'Joint Departmental Single-Window Inspection')], default='Pre-Establishment Site Visit', max_length=100)),
                ('status', models.CharField(choices=[('Scheduled', 'Inspection Scheduled'), ('Completed', 'Inspection Completed ✓'), ('Pending Report', 'Pending Field Report ⌛'), ('Rescheduled', 'Rescheduled ↻')], default='Scheduled', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='inspection_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='applications.application')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
