# Generated by Django 6.1.1 on 2026-09-29 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('user', 'Entrepreneur / Citizen'), ('assistant', 'Anumati Assistant AI')], default='user', max_length=20)),
                ('content', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=100)),
                ('context_sources', models.TextField(blank=True, help_text='Cited official rules, acts, or user profile records')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
