# Generated by Django 6.1.1 on 2026-09-29 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='e.g. dish-factory-plan, mpcb-cte', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_mr', models.CharField(blank=True, help_text='Marathi Official Name', max_length=255)),
                ('department', models.CharField(help_text='e.g. Directorate of Industrial Safety & Health (DISH)', max_length=255)),
                ('category', models.CharField(choices=[('Pre-Establishment', 'Pre-Establishment (Before Construction)'), ('Pre-Operation', 'Pre-Operation (Before Production)'), ('Post-Operation', 'Post-Operation (During Operations)'), ('Incentive', 'Incentive & Subsidy Claims')], default='Pre-Establishment', max_length=50)),
                ('why_required', models.TextField(help_text='Statutory justification and legal mandate')),
                ('eligibility', models.TextField(help_text='Units or criteria that must secure this approval')),
                ('expected_timeline_days', models.PositiveIntegerField(default=15)),
                ('sla_max_days', models.PositiveIntegerField(default=30, help_text='RTS Act statutory maximum disposal timeframe')),
                ('fee_structure', models.CharField(default='Statutory slab-based fee', max_length=255)),
                ('inspection_required', models.BooleanField(default=True)),
                ('renewal_period', models.CharField(default='One-time approval', max_length=100)),
                ('official_source', models.URLField(blank=True, default='https://maitri.mahaonline.gov.in', max_length=300)),
                ('applicable_sectors', models.TextField(default='Food Processing, Manufacturing, Automobile, Chemical, Textile', help_text='Comma-separated applicable sectors')),
                ('risk_category', models.CharField(choices=[('High', 'High Risk / Stringent Regulatory Audit'), ('Medium', 'Medium Risk / Standard Compliance'), ('Low', 'Low Risk / Fast-track Clearances')], default='High', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('doc_type_code', models.CharField(blank=True, help_text='e.g. factory_plan, environmental_noc, fire_layout', max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='approvals.approval')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
